# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-27 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='api_id')),
                ('date', models.CharField(max_length=11, verbose_name='日期')),
                ('title', models.CharField(max_length=25, verbose_name='标题')),
                ('tag', models.CharField(max_length=10, verbose_name='标签')),
                ('url', models.CharField(max_length=25, verbose_name='api_url')),
                ('file', models.CharField(max_length=256, verbose_name='api_file')),
                ('read', models.BigIntegerField(verbose_name='阅读量')),
            ],
        ),
    ]
