# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-27 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.CharField(default='blog', max_length=256, verbose_name='截取内容'),
            preserve_default=False,
        ),
    ]
